<script>
    require([
        'jquery',
        'prototype',
    ], function ($) {
        function exportAllProducts() {
            // params = {};
            // new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
            //     loaderArea: true,
            //     asynchronous: true,
            //     parameters: params,
            //     onSuccess: function (transport) {
            //         var response = JSON.parse(transport.responseText);
            //         $('#messages .message-success span.message-text').text('Your Controller Action Success Message Here');
            //         $('#messages .message-success').show();
            //         $('#messages .message-success').delay(8000).fadeOut();
            //     },
            //     onFailure: function() {               
            //         $('#messages .message-error span.message-text').text('Your Controller Action Failure Message Here');
            //         $('#messages .message-error').show();
            //         $('#messages .message-error').delay(8000).fadeOut();
            //         return false;
            //     }
            // });
            window.location.href = "<?php echo $block->getDownloadUrl() ?>";
        }
        $('#exportbtn').click(function () {
            exportAllProducts();
        });
    });
</script>
 
<div id="messages" >
    <div class="messages">
        <div class="message message-success success" style="display: none;">
            <div data-ui-id="messages-message-success">
                <span class="message-text"></span>
            </div>
        </div>
        <div class="message message-error error" style="display: none;">
            <div data-ui-id="messages-message-error">
                <span class="message-text"></span>
            </div>
        </div>
    </div>
</div>
<?php echo $block->getButtonHtml() ?>